version: "3"

services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: prework-linux-web
    volumes:
      - ".:/app"
    env_file:
      - .env
    ports:
      - "3001:3000"
    tty: true